# Imports

In [10]:
# # Imports

# ## Qutip imports 1

# In[1]:


from qutip.operators import sigmax, sigmay, sigmaz, identity
from qutip.operators import position, momentum, num, create, destroy, commutator, qeye 
from qutip.tensor import tensor
from qutip.qip.gates import swap, rx, ry, rz
from qutip.qobj import Qobj
from qutip.visualization import hinton
from qutip.visualization import matrix_histogram_complex, matrix_histogram
from qutip.random_objects import rand_herm, rand_unitary, rand_dm


# ## Qutip imports 2

# In[3]:


#from 


# ## Numpy imports 

# In[2]:


from numpy import sin, cos, tan, real, imag,  log, conj
from numpy import array, append, linspace, arange
from numpy import add, sqrt, abs, dot
from numpy.random import random, random_sample, rand, seed, RandomState
from numpy import concatenate, trace, diag
from numpy import ones, zeros, ones_like, zeros_like
from numpy import amax, amin, nanmax, nanmin
from numpy import outer, multiply
# from numpy import pi


# ## Scipy imports

# In[17]:


from scipy.integrate import ode, odeint, complex_ode
from scipy.optimize import minimize
from scipy.linalg import eigh, inv, norm, expm
# from scipy.linalg import 
# from scipy import


# ## Matplotlib imports

# In[18]:


from matplotlib.pyplot import plot, figure, show, savefig, axes
from matplotlib.pyplot import xlabel, ylabel, title, legend
from matplotlib import rcParams
from matplotlib.pyplot import style 
from matplotlib.pyplot import xlim, ylim, axis 
# beware not same as axes
from matplotlib.pyplot import subplot, subplots, text
from matplotlib.pyplot import GridSpec
from matplotlib.pyplot import scatter, colorbar


pgf_with_rc_fonts = {"pgf.texsystem": "pdflatex"}
rcParams.update(pgf_with_rc_fonts)
style.use('seaborn-whitegrid')


# ## Math imports

# In[19]:


from math import pi
from math import exp


# ## Cmath imports

# ## Date and datetime imports

# In[20]:


from datetime import date
from datetime import datetime# now


# ## Os imports

# In[21]:


from os import getcwd, mkdir, chdir
from os.path import abspath, join 


# ## Sympy imports

# In[22]:


from sympy import Function, dsolve, Eq, Derivative, symbols
# x, y, z, t = symbols('x y z t')
# k, m, n = symbols('k m n', integer=True)
# f, g, h = symbols('f g h', cls=Function)


# ## Miscellaneous imports

# ## Extra useful functions

# In[23]:


def rint(x):
    print("x = ", x)
    return None


# # Next chapter

# ## sub topic 1

# ## sub topic 2

# ## sub topic 3

# ### sub sub topic 1



# Trotter 

# Some  experimentation 

In [11]:
def calc_exp(X, h):
    rx, Ux = eigh(X)
    Ux_inv = inv(Ux)
    tx = diag(array([exp(h * i) for i in rx]))
    eX = Ux.dot(tx.dot(Ux_inv))
    return eX

In [12]:
x = rand_dm(5)
x

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 0.25322513+0.j         -0.00280148-0.00918549j  0.01460059+0.0178932j
   0.01206254-0.01335252j  0.03379939-0.01706656j]
 [-0.00280148+0.00918549j  0.07355258+0.j          0.04964452-0.01482532j
  -0.04977092+0.0703186j   0.04747544-0.03574526j]
 [ 0.01460059-0.0178932j   0.04964452+0.01482532j  0.12400114+0.j
  -0.08433786+0.00376657j -0.08100559-0.11784326j]
 [ 0.01206254+0.01335252j -0.04977092-0.0703186j  -0.08433786-0.00376657j
   0.12914005+0.j          0.02369353-0.02429532j]
 [ 0.03379939+0.01706656j  0.04747544+0.03574526j -0.08100559+0.11784326j
   0.02369353+0.02429532j  0.42008111+0.j        ]]

In [14]:
x.expm()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 1.28977546+0.j         -0.00253011-0.01002488j  0.01647771+0.02564919j
   0.01512545-0.01674298j  0.04790393-0.02668846j]
 [-0.00253011+0.01002488j  1.08410256+0.j          0.05769431-0.01444782j
  -0.0563348 +0.07900082j  0.0580147 -0.04710707j]
 [ 0.01647771-0.02564919j  0.05769431+0.01444782j  1.1507914 +0.j
  -0.09765944+0.00268795j -0.10659269-0.15601171j]
 [ 0.01512545+0.01674298j -0.0563348 -0.07900082j -0.09765944-0.00268795j
   1.14702705+0.j          0.03287395-0.02650922j]
 [ 0.04790393+0.02668846j  0.0580147 +0.04710707j -0.10659269+0.15601171j
   0.03287395+0.02650922j  1.54041341+0.j        ]]

In [13]:
rand_dm(5, 0.5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 0.20893842+0.j          0.04867841+0.03285247j  0.05760011-0.10099341j
   0.04020313-0.00850648j -0.0087758 -0.0819307j ]
 [ 0.04867841-0.03285247j  0.09172029+0.j          0.01607646+0.00338449j
   0.04137562-0.04278858j  0.05534399+0.05676411j]
 [ 0.05760011+0.10099341j  0.01607646-0.00338449j  0.26824051+0.j
   0.        +0.j          0.00325019-0.03928051j]
 [ 0.04020313+0.00850648j  0.04137562+0.04278858j  0.        +0.j
   0.04164905+0.j          0.02050834+0.06152456j]
 [-0.0087758 +0.0819307j   0.05534399-0.05676411j  0.00325019+0.03928051j
   0.02050834-0.06152456j  0.38945173+0.j        ]]

In [22]:
# calc_exp(x, 1) # gives error
'''
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-8c6bf0860ea3> in <module>()
----> 1 calc_exp(x, 1)

<ipython-input-11-b8d453701b72> in calc_exp(X, h)
      1 def calc_exp(X, h):
----> 2     rx, Ux = eigh(X)
      3     Ux_inv = inv(Ux)
      4     tx = diag(array([exp(h * i) for i in rx]))
      5     eX = Ux.dot(tx.dot(Ux_inv))

/anaconda3/envs/qutip-env/lib/python3.6/site-packages/scipy/linalg/decomp.py in
eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals, type,
check_finite)
    372 
    373     """
--> 374     a1 = _asarray_validated(a, check_finite=check_finite)
    375     if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:
    376         raise ValueError('expected square matrix')

/anaconda3/envs/qutip-env/lib/python3.6/site-packages/scipy/_lib/_util.py in 
_asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    239     if not objects_ok:
    240         if a.dtype is np.dtype('O'):
--> 241             raise ValueError('object arrays are not supported')
    242     if as_inexact:
    243         if not np.issubdtype(a.dtype, np.inexact):

ValueError: object arrays are not supported
'''

'\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n<ipython-input-15-8c6bf0860ea3> in <module>()\n----> 1 calc_exp(x, 1)\n\n<ipython-input-11-b8d453701b72> in calc_exp(X, h)\n      1 def calc_exp(X, h):\n----> 2     rx, Ux = eigh(X)\n      3     Ux_inv = inv(Ux)\n      4     tx = diag(array([exp(h * i) for i in rx]))\n      5     eX = Ux.dot(tx.dot(Ux_inv))\n\n/anaconda3/envs/qutip-env/lib/python3.6/site-packages/scipy/linalg/decomp.py in\neigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals, type,\ncheck_finite)\n    372 \n    373     """\n--> 374     a1 = _asarray_validated(a, check_finite=check_finite)\n    375     if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:\n    376         raise ValueError(\'expected square matrix\')\n\n/anaconda3/envs/qutip-env/lib/python3.6/site-packages/scipy/_lib/_util.py in \n_asarray_validated(a, check_finite, sparse_ok, obje

In [24]:
x_numpy = x.full()
x_numpy

array([[ 0.25322513+0.j        , -0.00280148-0.00918549j,
         0.01460059+0.0178932j ,  0.01206254-0.01335252j,
         0.03379939-0.01706656j],
       [-0.00280148+0.00918549j,  0.07355258+0.j        ,
         0.04964452-0.01482532j, -0.04977092+0.0703186j ,
         0.04747544-0.03574526j],
       [ 0.01460059-0.0178932j ,  0.04964452+0.01482532j,
         0.12400114+0.j        , -0.08433786+0.00376657j,
        -0.08100559-0.11784326j],
       [ 0.01206254+0.01335252j, -0.04977092-0.0703186j ,
        -0.08433786-0.00376657j,  0.12914005+0.j        ,
         0.02369353-0.02429532j],
       [ 0.03379939+0.01706656j,  0.04747544+0.03574526j,
        -0.08100559+0.11784326j,  0.02369353+0.02429532j,
         0.42008111+0.j        ]])

In [25]:
calc_exp(x_numpy, 1)

array([[ 1.28977546+4.52671947e-17j, -0.00253011-1.00248774e-02j,
         0.01647771+2.56491907e-02j,  0.01512545-1.67429787e-02j,
         0.04790393-2.66884642e-02j],
       [-0.00253011+1.00248774e-02j,  1.08410256+0.00000000e+00j,
         0.05769431-1.44478209e-02j, -0.0563348 +7.90008198e-02j,
         0.0580147 -4.71070663e-02j],
       [ 0.01647771-2.56491907e-02j,  0.05769431+1.44478209e-02j,
         1.1507914 +2.77555756e-17j, -0.09765944+2.68795436e-03j,
        -0.10659269-1.56011713e-01j],
       [ 0.01512545+1.67429787e-02j, -0.0563348 -7.90008198e-02j,
        -0.09765944-2.68795436e-03j,  1.14702705-5.55111512e-17j,
         0.03287395-2.65092240e-02j],
       [ 0.04790393+2.66884642e-02j,  0.0580147 +4.71070663e-02j,
        -0.10659269+1.56011713e-01j,  0.03287395+2.65092240e-02j,
         1.54041341-1.11022302e-16j]])

In [26]:
x.expm()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 1.28977546+0.j         -0.00253011-0.01002488j  0.01647771+0.02564919j
   0.01512545-0.01674298j  0.04790393-0.02668846j]
 [-0.00253011+0.01002488j  1.08410256+0.j          0.05769431-0.01444782j
  -0.0563348 +0.07900082j  0.0580147 -0.04710707j]
 [ 0.01647771-0.02564919j  0.05769431+0.01444782j  1.1507914 +0.j
  -0.09765944+0.00268795j -0.10659269-0.15601171j]
 [ 0.01512545+0.01674298j -0.0563348 -0.07900082j -0.09765944-0.00268795j
   1.14702705+0.j          0.03287395-0.02650922j]
 [ 0.04790393+0.02668846j  0.0580147 +0.04710707j -0.10659269+0.15601171j
   0.03287395+0.02650922j  1.54041341+0.j        ]]

In [27]:
x.expm().full()

array([[ 1.28977546+0.j        , -0.00253011-0.01002488j,
         0.01647771+0.02564919j,  0.01512545-0.01674298j,
         0.04790393-0.02668846j],
       [-0.00253011+0.01002488j,  1.08410256+0.j        ,
         0.05769431-0.01444782j, -0.0563348 +0.07900082j,
         0.0580147 -0.04710707j],
       [ 0.01647771-0.02564919j,  0.05769431+0.01444782j,
         1.1507914 +0.j        , -0.09765944+0.00268795j,
        -0.10659269-0.15601171j],
       [ 0.01512545+0.01674298j, -0.0563348 -0.07900082j,
        -0.09765944-0.00268795j,  1.14702705+0.j        ,
         0.03287395-0.02650922j],
       [ 0.04790393+0.02668846j,  0.0580147 +0.04710707j,
        -0.10659269+0.15601171j,  0.03287395+0.02650922j,
         1.54041341+0.j        ]])

In [16]:
y = random_sample((5,5))
y

array([[0.27205556, 0.61001336, 0.29043862, 0.6305682 , 0.14266139],
       [0.98435904, 0.92044159, 0.31801055, 0.2122036 , 0.40908942],
       [0.69602564, 0.95119093, 0.02373964, 0.30434583, 0.27606274],
       [0.43490666, 0.3021453 , 0.73361499, 0.89903215, 0.70860999],
       [0.15335212, 0.15742766, 0.22655492, 0.42037351, 0.89364306]])

In [17]:
calc_exp(y, 1)

array([[3.77473409, 4.09155223, 3.10466352, 2.69096671, 1.33412728],
       [4.09155223, 6.03507384, 4.00520233, 3.15071296, 1.60512368],
       [3.10466352, 4.00520233, 3.64403952, 3.02902376, 1.48914566],
       [2.69096671, 3.15071296, 3.02902376, 4.39093205, 1.85309651],
       [1.33412728, 1.60512368, 1.48914566, 1.85309651, 3.028495  ]])

In [18]:
yq = Qobj(y)
yq

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.27205556 0.61001336 0.29043862 0.6305682  0.14266139]
 [0.98435904 0.92044159 0.31801055 0.2122036  0.40908942]
 [0.69602564 0.95119093 0.02373964 0.30434583 0.27606274]
 [0.43490666 0.3021453  0.73361499 0.89903215 0.70860999]
 [0.15335212 0.15742766 0.22655492 0.42037351 0.89364306]]

In [19]:
yq.expm()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[2.76799833 2.25194118 1.2713279  2.01682311 1.47101693]
 [2.97422371 4.23055101 1.51606627 1.98617991 2.07662682]
 [2.35769035 2.81953996 2.06258036 1.76919454 1.67384205]
 [2.43792682 2.56234462 2.13807181 4.02211586 2.83778398]
 [1.17725749 1.28655793 1.01742811 1.62220124 3.2823878 ]]